//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIST.SUIST.Services.Test.ClienteServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDC", Namespace="http://schemas.datacontract.org/2004/07/DIST.SUIST.Services")]
    [System.SerializableAttribute()]
    public partial class ClienteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DIST.SUIST.Services.Test.ClienteServices.AuditoriaDC AuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInicioContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SitioWebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DIST.SUIST.Services.Test.ClienteServices.TipoClienteDC TipoClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DIST.SUIST.Services.Test.ClienteServices.AuditoriaDC Auditoria {
            get {
                return this.AuditoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditoriaField, value) != true)) {
                    this.AuditoriaField = value;
                    this.RaisePropertyChanged("Auditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoIdentidad {
            get {
                return this.DocumentoIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoIdentidadField, value) != true)) {
                    this.DocumentoIdentidadField = value;
                    this.RaisePropertyChanged("DocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinContrato {
            get {
                return this.FechaFinContratoField;
            }
            set {
                if ((this.FechaFinContratoField.Equals(value) != true)) {
                    this.FechaFinContratoField = value;
                    this.RaisePropertyChanged("FechaFinContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicioContrato {
            get {
                return this.FechaInicioContratoField;
            }
            set {
                if ((this.FechaInicioContratoField.Equals(value) != true)) {
                    this.FechaInicioContratoField = value;
                    this.RaisePropertyChanged("FechaInicioContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SitioWeb {
            get {
                return this.SitioWebField;
            }
            set {
                if ((object.ReferenceEquals(this.SitioWebField, value) != true)) {
                    this.SitioWebField = value;
                    this.RaisePropertyChanged("SitioWeb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DIST.SUIST.Services.Test.ClienteServices.TipoClienteDC TipoCliente {
            get {
                return this.TipoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoClienteField, value) != true)) {
                    this.TipoClienteField = value;
                    this.RaisePropertyChanged("TipoCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuditoriaDC", Namespace="http://schemas.datacontract.org/2004/07/DIST.SUIST.Services")]
    [System.SerializableAttribute()]
    public partial class AuditoriaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoClienteDC", Namespace="http://schemas.datacontract.org/2004/07/DIST.SUIST.Services")]
    [System.SerializableAttribute()]
    public partial class TipoClienteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DIST.SUIST.Services.Test.ClienteServices.AuditoriaDC AuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DIST.SUIST.Services.Test.ClienteServices.AuditoriaDC Auditoria {
            get {
                return this.AuditoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditoriaField, value) != true)) {
                    this.AuditoriaField = value;
                    this.RaisePropertyChanged("Auditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoCliente {
            get {
                return this.IdTipoClienteField;
            }
            set {
                if ((this.IdTipoClienteField.Equals(value) != true)) {
                    this.IdTipoClienteField = value;
                    this.RaisePropertyChanged("IdTipoCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteExcption", Namespace="http://schemas.datacontract.org/2004/07/DIST.SUIST.Services")]
    [System.SerializableAttribute()]
    public partial class ClienteExcption : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodError {
            get {
                return this.CodErrorField;
            }
            set {
                if ((this.CodErrorField.Equals(value) != true)) {
                    this.CodErrorField = value;
                    this.RaisePropertyChanged("CodError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescError {
            get {
                return this.DescErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.DescErrorField, value) != true)) {
                    this.DescErrorField = value;
                    this.RaisePropertyChanged("DescError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteServices.IClienteServices")]
    public interface IClienteServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteServices/ListarClientes", ReplyAction="http://tempuri.org/IClienteServices/ListarClientesResponse")]
        DIST.SUIST.Services.Test.ClienteServices.ClienteDC[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteServices/ListarClientes", ReplyAction="http://tempuri.org/IClienteServices/ListarClientesResponse")]
        System.Threading.Tasks.Task<DIST.SUIST.Services.Test.ClienteServices.ClienteDC[]> ListarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteServices/ListarTipoClientes", ReplyAction="http://tempuri.org/IClienteServices/ListarTipoClientesResponse")]
        DIST.SUIST.Services.Test.ClienteServices.TipoClienteDC[] ListarTipoClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteServices/ListarTipoClientes", ReplyAction="http://tempuri.org/IClienteServices/ListarTipoClientesResponse")]
        System.Threading.Tasks.Task<DIST.SUIST.Services.Test.ClienteServices.TipoClienteDC[]> ListarTipoClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteServices/ObtenerCliente", ReplyAction="http://tempuri.org/IClienteServices/ObtenerClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DIST.SUIST.Services.Test.ClienteServices.ClienteExcption), Action="http://tempuri.org/IClienteServices/ObtenerClienteClienteExcptionFault", Name="ClienteExcption", Namespace="http://schemas.datacontract.org/2004/07/DIST.SUIST.Services")]
        DIST.SUIST.Services.Test.ClienteServices.ClienteDC ObtenerCliente(int IdCliente, string DocumentoIdentidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteServices/ObtenerCliente", ReplyAction="http://tempuri.org/IClienteServices/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<DIST.SUIST.Services.Test.ClienteServices.ClienteDC> ObtenerClienteAsync(int IdCliente, string DocumentoIdentidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteServices/GuardarCliente", ReplyAction="http://tempuri.org/IClienteServices/GuardarClienteResponse")]
        bool GuardarCliente(DIST.SUIST.Services.Test.ClienteServices.ClienteDC objCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteServices/GuardarCliente", ReplyAction="http://tempuri.org/IClienteServices/GuardarClienteResponse")]
        System.Threading.Tasks.Task<bool> GuardarClienteAsync(DIST.SUIST.Services.Test.ClienteServices.ClienteDC objCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteServices/EliminarCliente", ReplyAction="http://tempuri.org/IClienteServices/EliminarClienteResponse")]
        bool EliminarCliente(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteServices/EliminarCliente", ReplyAction="http://tempuri.org/IClienteServices/EliminarClienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarClienteAsync(int IdCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServicesChannel : DIST.SUIST.Services.Test.ClienteServices.IClienteServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServicesClient : System.ServiceModel.ClientBase<DIST.SUIST.Services.Test.ClienteServices.IClienteServices>, DIST.SUIST.Services.Test.ClienteServices.IClienteServices {
        
        public ClienteServicesClient() {
        }
        
        public ClienteServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DIST.SUIST.Services.Test.ClienteServices.ClienteDC[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public System.Threading.Tasks.Task<DIST.SUIST.Services.Test.ClienteServices.ClienteDC[]> ListarClientesAsync() {
            return base.Channel.ListarClientesAsync();
        }
        
        public DIST.SUIST.Services.Test.ClienteServices.TipoClienteDC[] ListarTipoClientes() {
            return base.Channel.ListarTipoClientes();
        }
        
        public System.Threading.Tasks.Task<DIST.SUIST.Services.Test.ClienteServices.TipoClienteDC[]> ListarTipoClientesAsync() {
            return base.Channel.ListarTipoClientesAsync();
        }
        
        public DIST.SUIST.Services.Test.ClienteServices.ClienteDC ObtenerCliente(int IdCliente, string DocumentoIdentidad) {
            return base.Channel.ObtenerCliente(IdCliente, DocumentoIdentidad);
        }
        
        public System.Threading.Tasks.Task<DIST.SUIST.Services.Test.ClienteServices.ClienteDC> ObtenerClienteAsync(int IdCliente, string DocumentoIdentidad) {
            return base.Channel.ObtenerClienteAsync(IdCliente, DocumentoIdentidad);
        }
        
        public bool GuardarCliente(DIST.SUIST.Services.Test.ClienteServices.ClienteDC objCliente) {
            return base.Channel.GuardarCliente(objCliente);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarClienteAsync(DIST.SUIST.Services.Test.ClienteServices.ClienteDC objCliente) {
            return base.Channel.GuardarClienteAsync(objCliente);
        }
        
        public bool EliminarCliente(int IdCliente) {
            return base.Channel.EliminarCliente(IdCliente);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarClienteAsync(int IdCliente) {
            return base.Channel.EliminarClienteAsync(IdCliente);
        }
    }
}
